# hexo-theme-miho
# https://github.com/wongminho/hexo-theme-miho

# Favicon of your site | 网站icon
favicon: /favicon.ico

# Header

# Keywords of your site | 网站关键字
keywords: PengXiang,Sean's Blog,Sean's site,seanin,px,site
# Head headline | 头部标题
header_title: Sean's Site
# Head description | 头部描述
header_description: 一个立志 JavaScript全栈 开发的技术博客
# Link to your logo | logo地址
logo: images/logo.png
# Link to your banner_img | 首页banner图地址
banner_img: images/banner.jpg
# Menu setting | 菜单设置
#  name:                  Font Awesome icon | Font Awesome 图标
#    title: Home          Title | 标题
#    url: //minhow.com    Url, absolute or relative path | 链接，绝对或相对路径
#    target: true         Whether to jump out | 是否跳出
menu:
  home:
    title: 主页
    url: home/
    target: false
  list-ul:
    title: 文章列表
    url: /
    target: false
#  archive:
#    title: 文章归档
#    url: archives/
#    target: false
  paper-plane-o:
    title: 作品展示
    url: project/
    target: false
  user:
    title: 关于
    url: about/
    target: false
# Social setting, use to display social information | 社交设置，用来展示社交信息
#  name:                  Font Awesome icon | Font Awesome 图标
#    title: Home          Icon title | 图标标题
#    url: //minhow.com    Url, absolute or relative path | 链接，绝对或相对路径
#    target: true         Whether to jump out | 是否跳出
social:
  home:
    title: Home
    url: /
    target: false
  github:
    title: Github
    url: https://github.com/seanin
    target: true
  copyright:
    title: CSDN Blog
    url: http://blog.csdn.net/arvin0?viewmode=list
    target: true
  weibo:
    title: Weibo
    url: http://weibo.com/1751482640/profile?topnav=1&wvr=6&is_all=1
    target: true
#  twitter:
#    title: Twitter
#    url: //twitter.com/huangminhow
#    target: true
  envelope-o:
    title: email
    url: http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=245803627@qq.com
    target: true
  #qq:
  #weixin:
  #snapchat:
  #telegram:
  #mail:
  #facebook:
  #google:
  #linkedin:

# Content

# Excerpt length | 摘录长度
excerpt_length: 190
# Excerpt link | 摘录链接
excerpt_link: more>>
# New window open link | 新窗口打开文章
open_new_link: false
# Article default cover picture，size：350*150 | 文章默认封面图，尺寸：350*150
cover_picture: images/banner.jpg
# Open background particles | 开启背景粒子
open_bg_particle: true
# Open animation in homepage and head | 开启主页及头部动画
open_animation: true

# Article

# Open toc | 是否开启toc
toc: true
# Open share | 是否开启分享
share: true

# Style customization | 样式定制
style:
  # Main color tone | 主色调
  main_color: '#0cc'

# Comments | 评论

# 畅言，输入appid和appkey
changyan_appid: false
changyan_appkey: false
# 友言，输入id
youyan_id: 2130339
# disqus
disqus: false

# Analytics | 分析
# 站长分析，输入站点id
cnzz_analytics: false
# 百度分析，输入key值
baidu_analytics: false
# google analytics | google分析
google_analytics: false

# Footer

# Access statistics | “不蒜子”访问量统计
access_counter:
  on: true
  site_uv: 总访客数：
  site_pv: 总访问量：

# Copyright Information | 版权信息
copyright: 2017 sean
